import React, { useState } from 'react'
import Head from 'next/head'
import data from "../data.json"

export default function Admission() {
    const [formData, setFormData] = useState({
        name: "",
        email: "",
        phone: "",
        message: ""
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData({
            ...formData,
            [name]: value
        });
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        // Add your form submission logic here
        console.log("Form submitted:", formData);
        // Optionally, you can reset the form fields after submission
        setFormData({
            name: "",
            email: "",
            phone: "",
            message: ""
        });
    };
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="shortcut icon" href="/logo_icon.png" type="image/x-icon" />
                <title>{data.titles.admission}</title>
            </Head>
            <main className='body__content'>
                <div className="container mx-auto px-4 py-8">
                    <h2 className="text-3xl font-bold text-center mb-8">Admission</h2>
                    <form onSubmit={handleSubmit} className="max-w-lg mx-auto">
                        <div className="mb-4">
                            <label htmlFor="name" className="block text-gray-700 font-semibold mb-2">Name</label>
                            <input type="text" id="name" name="name" value={formData.name} onChange={handleChange} className="w-full border rounded-lg py-2 px-4 focus:outline-none focus:border-blue-500" required />
                        </div>
                        <div className="mb-4">
                            <label htmlFor="email" className="block text-gray-700 font-semibold mb-2">Email</label>
                            <input type="email" id="email" name="email" value={formData.email} onChange={handleChange} className="w-full border rounded-lg py-2 px-4 focus:outline-none focus:border-blue-500" required />
                        </div>
                        <div className="mb-4">
                            <label htmlFor="phone" className="block text-gray-700 font-semibold mb-2">Phone</label>
                            <input type="text" id="phone" name="phone" value={formData.phone} onChange={handleChange} className="w-full border rounded-lg py-2 px-4 focus:outline-none focus:border-blue-500" required />
                        </div>
                        <div className="mb-4">
                            <label htmlFor="message" className="block text-gray-700 font-semibold mb-2">Message</label>
                            <textarea id="message" name="message" value={formData.message} onChange={handleChange} className="w-full border rounded-lg py-2 px-4 focus:outline-none focus:border-blue-500 h-32" required></textarea>
                        </div>
                        <div className="text-center">
                            <button type="submit" className="bg-blue-500 text-white py-2 px-6 rounded-lg font-semibold hover:bg-blue-600 focus:outline-none">Submit</button>
                        </div>
                    </form>
                </div>
            </main>
        </>
    )
}
