import Head from 'next/head'
import React from 'react'
import data from "../data.json"
export default function Classes() {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>{data.titles.classes}</title>
            </Head>
            <main className='body__content'>
                Classes
            </main>
        </>
    )
}
