import Head from 'next/head'
import React from 'react'

export default function Classes() {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>Schedule of Classes - Skull Skate Society</title>
            </Head>
            <main className='body__content'>
                Classes
            </main>
        </>
    )
}
