import Head from 'next/head'
import React from 'react'
import data from "../data.json"
export default function Events() {
    const events = [
        {
            title: "Skateboarding Competition",
            date: "March 25, 2024",
            location: "City Skate Park",
            description: "Join us for an exhilarating skateboarding competition featuring top skaters from across the country.",
            imageUrl: "skateboarding_competition.jpg"
        },
        {
            title: "Skateboarding Workshop",
            date: "April 10, 2024",
            location: "Skate Park Arena",
            description: "Learn the basics of skateboarding and improve your skills with expert guidance at our workshop.",
            imageUrl: "skateboarding_workshop.jpg"
        },
        // Add more events as needed
    ];
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="shortcut icon" href="/logo_icon.png" type="image/x-icon" />
                <title>{data.titles.events}</title>
            </Head>
            <main className='body__content'>
                <div className="container mx-auto px-4 py-8">
                    <h2 className="text-3xl font-bold text-center mb-8">Events</h2>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                        {events.map((event, index) => (
                            <div key={index} className="bg-white rounded-lg shadow-md overflow-hidden">
                                <img src={event.imageUrl} alt={event.title} className="w-full h-48 object-cover" />
                                <div className="p-4">
                                    <h3 className="text-xl font-semibold mb-2">{event.title}</h3>
                                    <p className="text-gray-600 mb-2">{event.date}</p>
                                    <p className="text-gray-700 mb-2">{event.location}</p>
                                    <p className="text-gray-800">{event.description}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </main>
        </>
    )
}
