import Head from 'next/head'
import React from 'react'

export default function Events() {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="shortcut icon" href="/logo_icon.png" type="image/x-icon" />
                <title>Events by Skull Skate Society</title>
            </Head>
            <main className='body__content'>
                Events
            </main>
        </>
    )
}
