import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/logo_icon.png" type="image/x-icon" />
        <title>Home - Skull Skate Society</title>
      </Head>
      <main className='body__content'>
        <div className="text-3xl">
          <h1>home</h1>
        </div>
      </main>
    </>
  )
}
