import Head from 'next/head'
import React from 'react'
import data from "../data.json"
export default function Story() {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>{data.titles.story}</title>
            </Head>
            <main className='body__content'>
                <h1>
                    story of why the company was founded
                </h1>
                <h1>
                    Highlight your background and your founding team's role
                </h1>
                <h1>
                    Document the evolution of the company
                </h1>
                <h1>
                    Document the mission and vision
                </h1>
            </main>
        </>
    )
}
